{{- if not .Values.rbac.only }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telepresence.fullname" . }}
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
  - name: api
    port: 8081
    targetPort: api
  {{- with .Values.tracing }}
  - name: grpc-trace
    port: {{ .grpcPort }}
    targetPort: "grpc-trace"
  {{- end }}

  selector:
    {{- include "telepresence.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.agentInjector.name }}
  namespace: {{ include "telepresence.namespace" . }}
  labels:
    {{- include "telepresence.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    {{- include "telepresence.selectorLabels" . | nindent 4 }}
{{- end }}
